### ISSUE TITLE
initial layout

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/edly#1]
Make the correct initial layout with basic features

**Comment by dorian2science** [comment]
c'est fait pour target les issues en gros

**Comment by dorian2science** [comment]
### top

**Comment by dorian2science** [comment]
a=\omega

**Comment by dorian2science** [comment]
quand je vais chercher juste les données c'est à peine plus rapide. Bon c'est pas aussi rapide que le png bien sur mais bon c'est decent.

**Comment by dorian2science** [comment]
![image](https://user-images.githubusercontent.com/75440048/160475466-a03cf335-3467-4c9a-8040-65c8d068307c.png)

**Comment by dorian2science** [comment]
j'ai display I et Vga simultanément. Assez rapide. Mais pas instantanné comme l'autre. A voir ce que tu en penses. Ce qui est pratique en envoyant la figure entirère est qu'elle est beaucoup plus rapide à générer en python car plotly de python dispose d'une librairie qui s'appelle plotly.express qui bosse bien avec pandas

**Comment by ronandrevon** [comment]
oui ca a l'air plutot bien a priori. Par contre j'ai cette erreur sur la console js : 
angular.js:15697 TypeError: Cannot read properties of undefined (reading 'layout')
    at app.js:12:15

**Comment by dorian2science** [comment]
et la figure est correctement envoyée en python ?

**Comment by ronandrevon** [comment]
Je ferme cette issue car globablement tout marche
