### ISSUE TITLE
miller indices table

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/edly#16]
- highlight on hover

**Comment by ronandrevon** [comment]
![1](https://user-images.githubusercontent.com/51826122/164780940-43092b78-ad4d-4728-a1a7-98622cec59fd.gif)

**Comment by dorianSylfen** [comment]
C'est pas tres clair pou rmoi. Quelle est la nouvelle fonctionnalité?

**Comment by ronandrevon** [comment]
Au debut du gif on voit que hover sur la table de miller active le hover sur la figure
