### ISSUE TITLE
Import experimental dataset files for automatic orientation 

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/edly#23]
Possibility to import: 
- [x] pets datasets 
- [x] xds datasets
- [x] dials datasets 
- [x] automatic experimental wavelength  retrieval

**Comment by dorian2science** [comment]
t'es plus en vacances ?

**Comment by laurapacoste** [comment]
[XDS_ASCII.txt](https://github.com/ronandrevon/edly/files/11311316/XDS_ASCII.txt)

**Comment by dagewa** [comment]
Interestingly, I discovered that item 12 in the `XDS_ASCII.HKL` reflection table is an angle called $\psi$, "which completely specifies diffraction geometry with respect to the unit cell axes" (https://xds.mr.mpg.de/html_doc/xds_files.html#XDS_ASCII.HKL)

See [Schwarzenbach and Flack](https://journals.iucr.org/j/issues/1989/06/00/sr0097/sr0097.pdf).

It should be possible to use this value to reconstruct the diffraction geometry, then.
