### ISSUE TITLE
add buttons 

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/edly#3]
## buttons :
    - toggle to pass to single analysis mode
    - upload : tiffs
    - upload : pets/dials processing
    - upload : simulated data  
    - display b0.beam_vs_thickness in either another window or aside of analysis

**Comment by dorian2science** [comment]
un petit screenshot serait le bienvenu éventuellement. Je viens de suscribe pour recevoir les emails automatiquement. Mais comment le faire pour tous les mise a jour du projets et pas par issue ?

**Comment by ronandrevon** [comment]
## button JSmol to visualise the structure
![edly#3](https://user-images.githubusercontent.com/51826122/161379678-13fb09fd-cb89-4470-996e-65394fd3f96d.png)

## buttons (with popups):
    - upload : exp tiffs data
    - upload : simulated data  
    - upload : pets/dials processed data

 ![edly#3_2](https://user-images.githubusercontent.com/51826122/161379679-107209e1-5c07-4480-b38f-0669f0a7ec43.png)
