### ISSUE TITLE
enhance plotly viewer 

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/edly#6]
1. add `rpx,rpy,Ipets` (see l.94 bw_app.py) data to the plotly graph 
2. show indices found in `b0.df_G['hkl']` when hovering over data points 
3. add a callback which adds/removes in a javascript array the `hkl` data point when clicking on it
4. use following markers  {Vga:diamond, Swa:triangle, I:Circle, Ipets:square)
5. add a background color (light blue) to the graph 
6. Show larger marker sizes
7. add `px` and `py` labels to the axes   
8. persistent xylims, selected legend

**Comment by dorian2science** [comment]
Please uncompress the fig.zip and load the fig.html in your web browser.
[fig.zip](https://github.com/ronandrevon/edly/files/8408093/fig.zip)

1. done but superimposed leads necessary to a second grid with xaxis and yaxis because rpx is not the same as px(see the fig.html)
2. done
3. take a bit more time 
4. done
5. done is this fine(see fig.html)? 2 properties : paper_bgcolor(someway bla
ck) and plot_bgcolor(someway blue). I guess you want the plot_bgcolor.--> give the html color code.
6. done
7. done

**Comment by dorian2science** [comment]
3. question : the point should be hidden I guess ? But if fully hidden then how do you know where to click to let it appear again  ?

**Comment by ronandrevon** [comment]
> should we keep only on hover the miller indices or fig.html is fine ?
> 3. question : the point should be hidden I guess ? But if fully hidden then how do you know where to click to let it appear again  ?
When you hover, the miller indices should be seen along with the active data points. Once we click on the data point it toggles the add/remove miller index to a javascript array that can be later sent to the server for further processing

**Comment by dorian2science** [comment]
> > should we keep only on hover the miller indices or fig.html is fine ?
> > 3. question : the point should be hidden I guess ? But if fully hidden then how do you know where to click to let it appear again  ?
> > When you hover, the miller indices should be seen along with the active data points. Once we click on the data point it toggles the add/remove miller index to a javascript array that can be later sent to the server for further processing

je suis pas sur de comprendre

**Comment by dorian2science** [comment]
tu as pu ouvrir la figure html?

**Comment by ronandrevon** [comment]
>     1. done but superimposed leads necessary to a second grid with xaxis and yaxis because rpx is not the same as px(see the fig.html)
yes but we can convert px to have the same scale as rpx and the locations should then match. Actually there is also an in-plane  rotation to apply but I know how to do that. Is it necessary to have  a second grid if so ? 
>     5. done is this fine(see fig.html)? 2 properties : paper_bgcolor(someway bla
>        ck) and plot_bgcolor(someway blue). I guess you want the plot_bgcolor.--> give the html color code.
It is good I just wanted something else than white background.

**Comment by dorian2science** [comment]
I should be done with all plotly enhancements. The click callback with the table was quite easy to implement. The whole html/js script looks like this : 
```
<head>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
  <div id="myDiv" style="width: 100%;height:800px""></div>
  <h2>Table miller indices</h2>
  <table id="table_Miller_indices" border="1" cellpadding="2">
    <tr>
        <td>delete</td>
        <td><b>miller_indices</b></td>
    </tr>
  </table>

<script>
var TABLE_MILLER=document.getElementById('table_Miller_indices')
var datapts
Plotly.d3.json('/fig.json',function(fig){
  // console.log(fig);
  cool=JSON.parse(fig)
  Plotly.newPlot('myDiv', cool.data, cool.layout, {showSendToCloud: true});
  document.getElementById('myDiv').on('plotly_click', function(data){
    // console.log(data.points);
    datapts=data.points[0]
    addRow_tagTable(datapts.customdata)
  });
})

function addRow_tagTable(miller_indices) {
    if (!extract_list_indices_from_table().includes(miller_indices)) {
      var row = TABLE_MILLER.insertRow(TABLE_MILLER.rows.length);
      row.insertCell(0).innerHTML= '<input style="width:35px" type="button" value = "X" onClick="deleteRow(this)">';
      // row.insertCell(1).innerHTML= '<b>'+miller_indices+'</b>';
      row.insertCell(1).innerHTML= miller_indices;
  }
}
function extract_list_indices_from_table() {
  let listTags=[]
  let listrows= TABLE_MILLER.children[0].children
  for (let row of listrows) {
    // console.log(row.children[1].innerHTML);
    listTags.push(row.children[1].innerHTML)
  }
  return listTags.slice(1,)
}

function deleteRow(obj) {
    var index = obj.parentNode.parentNode.rowIndex;
    TABLE_MILLER.deleteRow(index);
}


</script>
</body>

```

**Comment by dorian2science** [comment]
Et la petite video qui va avec (extrait):
Uploading plotly_miller_shorter.mp4…

le fichier fig_json si tu veux tester rapidement. C'est project indépendant juste le bout de code ci-dessus fait le taf.
[fig_json.zip](https://github.com/ronandrevon/edly/files/8457783/fig_json.zip)

la video complete est sur gaston:

**Comment by dorian2science** [comment]
![image](https://user-images.githubusercontent.com/75440048/162592133-c06221db-e65d-4214-ac71-104df8ba2e77.png)

**Comment by dorian2science** [comment]
> Uploading plotly_miller_shorter.mp4…

bon j'ai l'impression que la vidéo ne s'uploade pas vraiment. Elle est sur champet ronan_backdoor
