### ISSUE TITLE
Menu for choosing the side figure data

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/edly#9]
- dropdown menu for the side figure available data to show (could be rocking curve, thickness dependent intensities if available)

**Comment by ronandrevon** [comment]
- plotly menu for the curves to show
- use `b0_path` to fix beam_vs_thickness update in rock mode
- `show_u` includes all orientation in auto mode (very slow)
- click enter on rock frame for specifying input
- change graphs layout to align dropdown menu nicely


![1](https://user-images.githubusercontent.com/51826122/164492264-70eda302-a194-4e83-807b-a409a96f3ab4.gif)

**Comment by dorianSylfen** [comment]
du coup ca a été implémenté si je comprends bien. Or do I have something to do ?

**Comment by ronandrevon** [comment]
oui c bon je ferme l'issue
